server:
  port: 8800
  
spring:
  application:
    name: users-provider
  # RabbitMQ(Spring Cloud Bus, Zipkin)
  rabbitmq:
    host: localhost
    password: 123
    port: 5672
    username: admin
  # zipkin HTTP 收集
#  zipkin: 
#    baseUrl: http://127.0.0.1:9411
#    sender:
#      type: web
  # Sleuth  
  sleuth: 
    sampler: 
      probability: 1.0 # 采样率，默认为 0.1。1.0 为完全收集，收集比例越大，收集发送服务对服务器影响越大，同时对存储压力也很大。
    


eureka:
  # Eureka Config
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
#      defaultZone: http://admin:123@localhost:8700/eureka/
      defaultZone: http://admin:123@localhost:8700/eureka/,http://admin:123@host2:8701/eureka/,http://admin:123@host3:8702/eureka/
  # Register Config
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    preferIpAddress: true
    # USED ONLY IN DEVELOPMENT MODE
    leaseExpirationDurationInSeconds: 90 # Expiration duration
    leaseRenewalIntervalInSeconds: 30  # Renewal update frequency
    
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh
#        include: hystrix.stream,health,info
#        include: *

# Error
error:
  path: /error
  
  

 